### ISSUE TITLE
Potential error

### ISSUE THREAD

**Issue by azimanabdullah** [MoH-Malaysia/covid19-public#70] opened 2021-07-28 02:43 UTC
I found potential errors in cases_state.csv as followed:
Line 1041 : 2020-05-19, W.P. Putrajaya , -1
Line 4783 : 2021-01-08, W.P. Kuala Lumpur, -101

I have cross-checked with KKM website, the actual cases for both dates are:
2020-05-19, W.P. Putrajaya , 0 (https://covid-19.moh.gov.my/terkini/052020/situasi-terkini-19-mei-2020)
2021-01-08, W.P. Kuala Lumpur, 282 (https://covid-19.moh.gov.my/terkini-negeri/2021/01/kemaskini-negeri-covid-19-di-malaysia-sehingga-08012021)

Thanks.

**Comment by chonggs** [comment] 2021-07-28 03:17
Duplicate of #26. 
@MoH-Malaysia Can we please leave unresolved issues Open? So that others can be aware of them.

**Comment by KennethThePro** [comment] 2021-07-31 13:54
The negative values are likely due to the number of cases that are not accurate in the previous day(s) when entering the data.

For W.P. Kuala Lumpur:
On the 7th of January 2021, W.P. Kuala Lumpur reported 316 new cases, and on the 8th of January 2021, W.P. Kuala Lumpur reported 282 new cases. The total number of new cases in W.P. Kuala Lumpur is 598 in these two days.
2021-01-07: [https://covid-19.moh.gov.my/terkini-negeri/2021/01/kemaskini-negeri-covid-19-di-malaysia-sehingga-07012021](url)

However, in the cases_state.csv, it states that there are 699 new cases on the 7th of January 2021, which is already an excess of 383 new cases reported. With 282 new cases on the 8th of January 2021, 383 - 282 results in an final excess of 101 cases.

For W.P. Putrajaya
On the 19th of May 2020, For W.P. Putrajaya reported no cases, and on the 20th of May 2020, For W.P. Putrajaya reported 2 new cases. The total number of new cases in For W.P. Putrajaya is 2 in these two days.
2021-05-20: [https://covid-19.moh.gov.my/terkini/052020/situasi-terkini-20-mei-2020](url)

However, in the cases_state.csv, it states that there are -1 new cases on the 19th of May 2020. On the 20th of May 2020, it states a total of 3 cases, which is probably intended to balance the cases to a total of 2 cases.

These are probably not the only two errors since I have to manage to find some other inaccurate number of cases in some states on other dates.

**Comment by MoH-Malaysia** [comment] 2021-08-10 08:49
This has been fixed!

**Closed by MoH-Malaysia** 2021-08-10 08:49 UTC
