### ISSUE TITLE
clusters csv file extra new line character problem on line 128

### ISSUE THREAD

**Issue by leeliwei930** [MoH-Malaysia/covid19-public#66] opened 2021-07-27 10:21 UTC
There is an extra newline character that caused the data to pre-process library (danfo.js) unable to parse the clusters.csv suggest removing the extra newline character on line 128 to line 130.

![Screenshot 2021-07-27 at 6 19 46 PM](https://user-images.githubusercontent.com/11514728/127138172-f329a039-f126-4967-a290-eeeb07a6c736.png)

**Comment by chonggs** [comment] 2021-07-27 10:39
Duplicate of #16 
Can it be fixed? @MoH-Malaysia

**Comment by MoH-Malaysia** [comment] 2021-07-27 12:01
Thank you!

**Closed by MoH-Malaysia** 2021-07-27 12:01 UTC
